branch-defaults:
  default:
    environment: django-env
    group_suffix: null
global:
  application_name: django-tutorial
  default_ec2_keyname: aws-eb
  default_platform: python
  default_region: us-west-2
  profile: eb-cli
  sc: null
